"""Verify a Mailgent webhook signature.

Mailgent sends ``X-Mailgent-Signature: sha256=<hex>`` — an HMAC-SHA256 of
the raw request body using the project's webhook secret. Pass the raw
body bytes the request arrived with (don't re-stringify the JSON).

    from mailgent.webhook import verify_webhook

    @app.post("/webhooks/mailgent")
    async def webhook(request: Request):
        ok = verify_webhook(
            await request.body(),
            request.headers.get("x-mailgent-signature"),
            os.environ["MAILGENT_WEBHOOK_SECRET"],
        )
        if not ok:
            raise HTTPException(400, "invalid signature")
        # de-dupe on x-mailgent-idempotency-key, then handle.
        # Today the only event type is `payment.received`.

The webhook secret is generated by Mailgent when you register an endpoint
in the Console and shown to you exactly once. If you lose it, rotate
to get a new one.
"""

from __future__ import annotations

import hashlib
import hmac
import re
from typing import Optional, Union

_HEX_RE = re.compile(r"^[0-9a-f]+$")


def verify_webhook(
    raw_body: Union[str, bytes],
    signature: Optional[str],
    secret: str,
) -> bool:
    """Return ``True`` iff ``signature`` matches HMAC-SHA256(secret, raw_body).

    Always rejects:
      - empty ``secret`` (an unset env var would otherwise HMAC with an
        empty key and any attacker who guesses that could forge);
      - missing or empty ``signature``;
      - signatures without the ``sha256=`` prefix;
      - signatures whose hex portion contains non-hex characters.
    """
    if not secret:
        return False
    if not signature or not signature.startswith("sha256="):
        return False
    provided = signature[7:].lower()
    if not _HEX_RE.match(provided):
        return False

    body_bytes = raw_body if isinstance(raw_body, bytes) else raw_body.encode("utf-8")
    expected = hmac.new(
        secret.encode("utf-8"),
        body_bytes,
        hashlib.sha256,
    ).hexdigest()
    return hmac.compare_digest(provided, expected)


__all__ = ["verify_webhook"]
